// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3FVWoZpoIRZOxx9vt0ZmHBfuWy-t037U',
    appId: '1:448115347826:web:596fffa67db8ff43670deb',
    messagingSenderId: '448115347826',
    projectId: 'jpay-17',
    authDomain: 'jpay-17.firebaseapp.com',
    storageBucket: 'jpay-17.firebasestorage.app',
    measurementId: 'G-1HK0Y1TYN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3v-x7EErwvW4Ti-sMoenNt0ypdZ2ceOI',
    appId: '1:448115347826:android:0a5094fb8f8dd9ec670deb',
    messagingSenderId: '448115347826',
    projectId: 'jpay-17',
    storageBucket: 'jpay-17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtK0spYy8bxV7c7wKlRoCYtbeq2Dh4nyc',
    appId: '1:448115347826:ios:06b5b267fc096fb3670deb',
    messagingSenderId: '448115347826',
    projectId: 'jpay-17',
    storageBucket: 'jpay-17.firebasestorage.app',
    iosBundleId: 'com.example.jpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtK0spYy8bxV7c7wKlRoCYtbeq2Dh4nyc',
    appId: '1:448115347826:ios:06b5b267fc096fb3670deb',
    messagingSenderId: '448115347826',
    projectId: 'jpay-17',
    storageBucket: 'jpay-17.firebasestorage.app',
    iosBundleId: 'com.example.jpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3FVWoZpoIRZOxx9vt0ZmHBfuWy-t037U',
    appId: '1:448115347826:web:62738cb8b1f85402670deb',
    messagingSenderId: '448115347826',
    projectId: 'jpay-17',
    authDomain: 'jpay-17.firebaseapp.com',
    storageBucket: 'jpay-17.firebasestorage.app',
    measurementId: 'G-KKJ52JW06Y',
  );
}
